// Code generated by mockery v2.53.5. DO NOT EDIT.

package wifi

import (
	mywifi "github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

// MockWiFiHandle is an autogenerated mock type for the WiFiHandle type
type MockWiFiHandle struct {
	mock.Mock
}

// Interfaces provides a mock function with no fields
func (_m *MockWiFiHandle) Interfaces() ([]*mywifi.Interface, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []*mywifi.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*mywifi.Interface, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*mywifi.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*mywifi.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockWiFiHandle creates a new instance of MockWiFiHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWiFiHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWiFiHandle {
	mock := &MockWiFiHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
